# -*- coding: utf-8 -*-
"""excel_dashboard.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PJp0umiAC8gj3VWgu7ksuc_zZYCTC5j5
"""

import streamlit as st
import pandas as pd

excel_file = 'train2.xls'
df = pd.read_excel(excel_file)

# Set a title for the app
st.title('Excel Data Visualization Dashboard')

# Display the raw data
st.subheader('Raw Data')
st.write(df)

# Create a bar chart
st.subheader('Bar Chart')
bar_chart = df.groupby('Product_Category_1')['Purchase'].sum()
st.bar_chart(bar_chart)

# Create a scatter plot
st.subheader('Scatter Plot')
scatter_plot = st.line_chart(df.groupby('Age')['Purchase'].sum())